// Example n8n workflow for JobSpy integration with LLM filtering
// This is a JavaScript code snippet that can be used in an n8n Execute JavaScript node

// Input parameters from previous nodes
const job = $input.item.json.job || "Software Engineer";
const location = $input.item.json.location || "London";
const contract = $input.item.json.contract === "Yes" ? true : false;
const remote = $input.item.json.remote === "Yes" ? true : false;
const country = $input.item.json.country || "UK";
const results = $input.item.json.results || 100;
const jobserveUrl = $input.item.json.jobserveUrl || "";
const useLlm = $input.item.json.useLlm === "Yes" ? true : false;
const apiKey = $input.item.json.apiKey || process.env.OPENAI_API_KEY;
const minScore = $input.item.json.minScore || 0.7;
const limit = $input.item.json.limit || 50;

// Generate unique filenames based on timestamp
const timestamp = new Date().toISOString().replace(/[:.]/g, '');
const outputFile = $input.item.json.output || `jobs_${timestamp}.csv`;
const filteredOutputFile = `filtered_${outputFile}`;

// Determine which command to execute based on whether LLM filtering is enabled
let command;

if (useLlm && apiKey) {
  // Use search_and_filter.sh if LLM filtering is enabled
  command = `cd ${__dirname} && ./search_and_filter.sh `;
  command += `Job="${job}" `;
  command += `Location="${location}" `;
  command += `Contract="${contract ? 'Yes' : 'No'}" `;
  command += `Remote="${remote ? 'Yes' : 'No'}" `;
  command += `Country="${country}" `;
  command += `Results=${results} `;
  command += `ApiKey="${apiKey}" `;
  command += `MinScore=${minScore} `;
  command += `Limit=${limit}`;
  
  // Add JobServe URL if provided
  if (jobserveUrl) {
    command += ` JobServeUrl="${jobserveUrl}"`;
  }
} else {
  // Use job_search.sh if LLM filtering is not enabled
  command = `cd ${__dirname} && ./job_search.sh `;
  command += `Job="${job}" `;
  command += `Location="${location}" `;
  command += `Contract="${contract ? 'Yes' : 'No'}" `;
  command += `Remote="${remote ? 'Yes' : 'No'}" `;
  command += `Country="${country}" `;
  command += `Results=${results} `;
  command += `Output="${outputFile}"`;
  
  // Add JobServe URL if provided
  if (jobserveUrl) {
    command += ` JobServeUrl="${jobserveUrl}"`;
  }
}

// Execute the command using the n8n exec function
const { exec } = require('child_process');

return new Promise((resolve, reject) => {
  exec(command, (error, stdout, stderr) => {
    if (error) {
      console.error(`Error: ${error.message}`);
      return reject(error);
    }
    if (stderr) {
      console.error(`stderr: ${stderr}`);
    }
    
    console.log(`stdout: ${stdout}`);
    
    // Return the output file path and command for the next node
    return resolve({
      command: command,
      output_file: outputFile,
      stdout: stdout
    });
  });
});

/*
Example n8n workflow:

1. HTTP Request node (to trigger the workflow)
   - Method: GET
   - URL: http://localhost:5678/webhook/jobspy
   - Authentication: None
   - Query Parameters:
     - job: Software Engineer
     - location: London
     - contract: Yes
     - remote: No
     - country: UK
     - results: 100
     - jobserveUrl: https://www.jobserve.com/gb/en/JobSearch.aspx?shid=A52743B548BF3DE25A4A (optional)
     - useLlm: Yes
     - apiKey: your-openai-api-key (optional if set in environment)
     - minScore: 0.7
     - limit: 50

2. Execute JavaScript node
   - Use the code above
   - This will execute either job_search.sh or search_and_filter.sh depending on whether LLM filtering is enabled

3. Read Binary File node
   - File Path: =data.output_file
   - This will read the CSV file generated by the script

4. HTTP Response node
   - Response Body: =data
   - This will return the CSV file to the client

Note: If LLM filtering is enabled, the script will generate two files:
1. A raw results file with all jobs found
2. A filtered results file with only the most relevant jobs
*/
